export const ADD_PLAYERS = 'ADD_PLAYERS';
export const INCLUDE_GAME_DEPENDENT_COMPONENT_VALUE = 'INCLUDE_GAME_DEPENDENT_COMPONENT_VALUE';
export const UPDATE_POINTS = 'UPDATE_POINTS';
export const STORE_POINTS = 'STORE_POINTS';
